### ISSUE TITLE
Relax phoenix_gon elixir version requirement

### ISSUE THREAD

**Issue by nietaki** [khusnetdinov/phoenix_gon#16]
`phoenix_gon` depends on Elixir 1.6 and when used with an earlier version generates a warning on compilation: `warning: the dependency :phoenix_gon requires Elixir "~> 1.6" but you are running on v1.5.1`

I didn't notice anything about `phoenix_gon` that relies on 1.6 features - am I missing something?

If there isn't an actual dependency on 1.6, the ` elixir: "~> 1.6",` line in `mix.exs` should be changed to point to an earliest supported version. "~> 1.4" would mean any version v: `1.4 <= v < 2.0` would be supported by the project.

**Comment by nietaki** [comment]
Also, it looks like 0.3.2 is on hex.pm but none of the earlier 0.3.x releases are. Did you remove them? I don't think it's a good practice.

**Comment by khusnetdinov** [comment]
Need to check

**Comment by khusnetdinov** [comment]
@nietaki You are right, but as I remember with those versions were problems with poison versions. So just check it. Thats why I updated to last elixir version.

**Comment by nietaki** [comment]
I don't follow, can you explain what the problem was in more detail? Poison should be working well on Elixir [1.4 upwards](https://github.com/devinus/poison/blob/master/mix.exs#L9) and I never had any problems with it.

**Comment by khusnetdinov** [comment]
Ok, I will release it

**Comment by khusnetdinov** [comment]
@nietaki Check 0.4.0 version and confirm that problem for you is solved.
