### ISSUE TITLE
compability spelling error.

### ISSUE THREAD

**Issue by CrowdHailer** [khusnetdinov/phoenix_gon#21]
Is this supposed to be `compatibility`?

also I can't see anywhere that struct key is used.

**Comment by khusnetdinov** [comment]
@CrowdHailer You are right, PR? )

**Comment by khusnetdinov** [comment]
@CrowdHailer this variable should be for compatibility with umbrella apps. But I haven't implemented it.

**Comment by khusnetdinov** [comment]
https://github.com/khusnetdinov/phoenix_gon/pull/22
