### ISSUE TITLE
Output sanitization

### ISSUE THREAD

**Issue by rmoorman** [khusnetdinov/phoenix_gon#6]
Hello,

Currently, phoenix_gon is using Poison.encode to encode the data and inserting it into a HTML script tag without further processing. This could lead to unsafe behaviour as HTML tags inside the variables are left untouched.

In javascript land, one would normally use something like [serialize-javascript](https://github.com/yahoo/serialize-javascript) in order to avoid potential issues.

It could be a good thing to adapt the aproach taken there (or something like  `JSON.stringify(state).replace(/</g, '\\u003c')`).

**Comment by khusnetdinov** [comment]
Could you explain more detailed cases?

**Comment by rmoorman** [comment]
Well, it boils down to this: one can add arbitrary data using phoenix_gon; that data is serialized to JSON and then rendered as part of a <script> tag that is added to the html output.
Due to the way the browser reads the html, unescaped html inside the json data can cause issues. 
Have a look at following example ([gist](https://gist.github.com/rmoorman/201721be88bf853c5984cc3e6ff3ee8d), [preview](https://cdn.rawgit.com/rmoorman/201721be88bf853c5984cc3e6ff3ee8d/raw/b56abc51a2c8977ff160d6cc698c4ee13b6fcdf7/index.html)):
~~~html
<!doctype html>
<title>test</title>
<script>
  var data = {"username": "foo", "tagline": "all your base</script><script>alert('are belong to us!')</script>"}
</script>
~~~
This will happily alert "are belong to us!" when you open the page. So in case the to be serialized and rendered data added to phoenix_gon is not sanitized this could form a attack vector.

Maybe you will find the following [article](https://medium.com/node-security/the-most-common-xss-vulnerability-in-react-js-applications-2bdffbcc1fa0) about this topic interesting.

Even though I didn't prepare a test project to check for the issue, the code in `lib/phoenix_gon/view.ex` suggests that no futher santization is done to prevent html inside the serialized data from triggering the behaviour mentioned above.

I could create a test project if you want (could take a while though for me to find some spare time for it..).

**Comment by rmoorman** [comment]
@khusnetdinov I prepared an example [over here](https://github.com/rmoorman/phoenix-gon-issue-6-example). It is basically the output of the phoenix scaffold without ecto and with phoenix_gon added on top.
Running the app and visiting the app in the browser will present you with an alert rather than the markup inside the gon assets and some malformed output on the page.

In case you have any more questions, feel free to ask and I will try to answer them.

While trying out phoenix_gon this way I also ran into a dependency issue with poison. I will file a separate issue for that.

**Comment by jabberfest** [comment]
Phoenix has a function called escape_javascript that is part of Phoenix.HTML. Couldn't you do something like

```
var phoenixAssets = #{escape_javascript(Poison.encode!(assets(conn)))};
```

See: https://hexdocs.pm/phoenix_html/Phoenix.HTML.html#escape_javascript/1

To @rmoorman initial concern, this was also a problem for the original Rails GON gem. They solved it in a similar manner.

See: https://github.com/gazay/gon/issues/25

**Comment by rmoorman** [comment]
Thank you @jabberfest for looking into it an providing a PR :-) I will give it a whirl.
