### ISSUE TITLE
Dependency problem with "vanilla" phoenix 1.3.0

### ISSUE THREAD

**Issue by rmoorman** [khusnetdinov/phoenix_gon#7]
I followed the phoenix_gon installation instructions in the readme but when I tried to fetch the dependency after altering the mix.exs file inside my project I got the following error:

~~~
$ mix deps.get
Resolving Hex dependencies...

Failed to use "poison" (version 3.1.0) because
  phoenix (version 1.3.0) requires ~> 2.2 or ~> 3.0
  phoenix_gon (version 0.2.0) requires ~> 2.0
  mix.lock specifies 3.1.0

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
~~~

which I resolved temporarily with `mix deps.update --all` which leaves me with poison version 2.2 which likely isn't what we want in the end.

**Comment by khusnetdinov** [comment]
Did you find versions that acceptable for resolving? Any Ideas?

**Comment by rmoorman** [comment]
From looking at the tags [2.2.0 and 3.1.0](https://github.com/devinus/poison/compare/2.2.0...3.1.0), it does not seem that the public api did change much. Also there seems to be some html related code addition for escaping that might  also affect/be used with the code changes introduced in #6 (through #8). I am not entitled to judge on that though 😄 imho.

**Comment by khusnetdinov** [comment]
I try to update versions.

**Comment by khusnetdinov** [comment]
Try to use code from 'master' branch, while I fox this problem

**Comment by khusnetdinov** [comment]
Use 0.3.2 version Fixed
